export const FETCH_PEOPLE = "FETCH_PEOPLE";
export const FETCHING_PEOPLE = "FETCHING_PEOPLE";
export const RESET_FETCH_PEOPLE = "RESET_FETCH_PEOPLE";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
